# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paula/Desktop/MDD-MH

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paula/Desktop/MDD-MH

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paula/Desktop/MDD-MH/CMakeFiles /home/paula/Desktop/MDD-MH//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paula/Desktop/MDD-MH/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paula/Desktop/MDD-MH/CMakeFiles /home/paula/Desktop/MDD-MH//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paula/Desktop/MDD-MH/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/AGE_posicion.o: src/AGE_posicion.cpp.o
.PHONY : src/AGE_posicion.o

# target to build an object file
src/AGE_posicion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGE_posicion.cpp.o
.PHONY : src/AGE_posicion.cpp.o

src/AGE_posicion.i: src/AGE_posicion.cpp.i
.PHONY : src/AGE_posicion.i

# target to preprocess a source file
src/AGE_posicion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGE_posicion.cpp.i
.PHONY : src/AGE_posicion.cpp.i

src/AGE_posicion.s: src/AGE_posicion.cpp.s
.PHONY : src/AGE_posicion.s

# target to generate assembly for a file
src/AGE_posicion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGE_posicion.cpp.s
.PHONY : src/AGE_posicion.cpp.s

src/AGE_uniforme.o: src/AGE_uniforme.cpp.o
.PHONY : src/AGE_uniforme.o

# target to build an object file
src/AGE_uniforme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGE_uniforme.cpp.o
.PHONY : src/AGE_uniforme.cpp.o

src/AGE_uniforme.i: src/AGE_uniforme.cpp.i
.PHONY : src/AGE_uniforme.i

# target to preprocess a source file
src/AGE_uniforme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGE_uniforme.cpp.i
.PHONY : src/AGE_uniforme.cpp.i

src/AGE_uniforme.s: src/AGE_uniforme.cpp.s
.PHONY : src/AGE_uniforme.s

# target to generate assembly for a file
src/AGE_uniforme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGE_uniforme.cpp.s
.PHONY : src/AGE_uniforme.cpp.s

src/AGG_posicion.o: src/AGG_posicion.cpp.o
.PHONY : src/AGG_posicion.o

# target to build an object file
src/AGG_posicion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGG_posicion.cpp.o
.PHONY : src/AGG_posicion.cpp.o

src/AGG_posicion.i: src/AGG_posicion.cpp.i
.PHONY : src/AGG_posicion.i

# target to preprocess a source file
src/AGG_posicion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGG_posicion.cpp.i
.PHONY : src/AGG_posicion.cpp.i

src/AGG_posicion.s: src/AGG_posicion.cpp.s
.PHONY : src/AGG_posicion.s

# target to generate assembly for a file
src/AGG_posicion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGG_posicion.cpp.s
.PHONY : src/AGG_posicion.cpp.s

src/AGG_uniforme.o: src/AGG_uniforme.cpp.o
.PHONY : src/AGG_uniforme.o

# target to build an object file
src/AGG_uniforme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGG_uniforme.cpp.o
.PHONY : src/AGG_uniforme.cpp.o

src/AGG_uniforme.i: src/AGG_uniforme.cpp.i
.PHONY : src/AGG_uniforme.i

# target to preprocess a source file
src/AGG_uniforme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGG_uniforme.cpp.i
.PHONY : src/AGG_uniforme.cpp.i

src/AGG_uniforme.s: src/AGG_uniforme.cpp.s
.PHONY : src/AGG_uniforme.s

# target to generate assembly for a file
src/AGG_uniforme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AGG_uniforme.cpp.s
.PHONY : src/AGG_uniforme.cpp.s

src/AM_1.o: src/AM_1.cpp.o
.PHONY : src/AM_1.o

# target to build an object file
src/AM_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_1.cpp.o
.PHONY : src/AM_1.cpp.o

src/AM_1.i: src/AM_1.cpp.i
.PHONY : src/AM_1.i

# target to preprocess a source file
src/AM_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_1.cpp.i
.PHONY : src/AM_1.cpp.i

src/AM_1.s: src/AM_1.cpp.s
.PHONY : src/AM_1.s

# target to generate assembly for a file
src/AM_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_1.cpp.s
.PHONY : src/AM_1.cpp.s

src/AM_2.o: src/AM_2.cpp.o
.PHONY : src/AM_2.o

# target to build an object file
src/AM_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_2.cpp.o
.PHONY : src/AM_2.cpp.o

src/AM_2.i: src/AM_2.cpp.i
.PHONY : src/AM_2.i

# target to preprocess a source file
src/AM_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_2.cpp.i
.PHONY : src/AM_2.cpp.i

src/AM_2.s: src/AM_2.cpp.s
.PHONY : src/AM_2.s

# target to generate assembly for a file
src/AM_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_2.cpp.s
.PHONY : src/AM_2.cpp.s

src/AM_3.o: src/AM_3.cpp.o
.PHONY : src/AM_3.o

# target to build an object file
src/AM_3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_3.cpp.o
.PHONY : src/AM_3.cpp.o

src/AM_3.i: src/AM_3.cpp.i
.PHONY : src/AM_3.i

# target to preprocess a source file
src/AM_3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_3.cpp.i
.PHONY : src/AM_3.cpp.i

src/AM_3.s: src/AM_3.cpp.s
.PHONY : src/AM_3.s

# target to generate assembly for a file
src/AM_3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_3.cpp.s
.PHONY : src/AM_3.cpp.s

src/AM_comun.o: src/AM_comun.cpp.o
.PHONY : src/AM_comun.o

# target to build an object file
src/AM_comun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_comun.cpp.o
.PHONY : src/AM_comun.cpp.o

src/AM_comun.i: src/AM_comun.cpp.i
.PHONY : src/AM_comun.i

# target to preprocess a source file
src/AM_comun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_comun.cpp.i
.PHONY : src/AM_comun.cpp.i

src/AM_comun.s: src/AM_comun.cpp.s
.PHONY : src/AM_comun.s

# target to generate assembly for a file
src/AM_comun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AM_comun.cpp.s
.PHONY : src/AM_comun.cpp.s

src/MDD.o: src/MDD.cpp.o
.PHONY : src/MDD.o

# target to build an object file
src/MDD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MDD.cpp.o
.PHONY : src/MDD.cpp.o

src/MDD.i: src/MDD.cpp.i
.PHONY : src/MDD.i

# target to preprocess a source file
src/MDD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MDD.cpp.i
.PHONY : src/MDD.cpp.i

src/MDD.s: src/MDD.cpp.s
.PHONY : src/MDD.s

# target to generate assembly for a file
src/MDD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MDD.cpp.s
.PHONY : src/MDD.cpp.s

src/brutesearch.o: src/brutesearch.cpp.o
.PHONY : src/brutesearch.o

# target to build an object file
src/brutesearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/brutesearch.cpp.o
.PHONY : src/brutesearch.cpp.o

src/brutesearch.i: src/brutesearch.cpp.i
.PHONY : src/brutesearch.i

# target to preprocess a source file
src/brutesearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/brutesearch.cpp.i
.PHONY : src/brutesearch.cpp.i

src/brutesearch.s: src/brutesearch.cpp.s
.PHONY : src/brutesearch.s

# target to generate assembly for a file
src/brutesearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/brutesearch.cpp.s
.PHONY : src/brutesearch.cpp.s

src/greedy.o: src/greedy.cpp.o
.PHONY : src/greedy.o

# target to build an object file
src/greedy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/greedy.cpp.o
.PHONY : src/greedy.cpp.o

src/greedy.i: src/greedy.cpp.i
.PHONY : src/greedy.i

# target to preprocess a source file
src/greedy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/greedy.cpp.i
.PHONY : src/greedy.cpp.i

src/greedy.s: src/greedy.cpp.s
.PHONY : src/greedy.s

# target to generate assembly for a file
src/greedy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/greedy.cpp.s
.PHONY : src/greedy.cpp.s

src/localsearch_rand.o: src/localsearch_rand.cpp.o
.PHONY : src/localsearch_rand.o

# target to build an object file
src/localsearch_rand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/localsearch_rand.cpp.o
.PHONY : src/localsearch_rand.cpp.o

src/localsearch_rand.i: src/localsearch_rand.cpp.i
.PHONY : src/localsearch_rand.i

# target to preprocess a source file
src/localsearch_rand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/localsearch_rand.cpp.i
.PHONY : src/localsearch_rand.cpp.i

src/localsearch_rand.s: src/localsearch_rand.cpp.s
.PHONY : src/localsearch_rand.s

# target to generate assembly for a file
src/localsearch_rand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/localsearch_rand.cpp.s
.PHONY : src/localsearch_rand.cpp.s

src/pincrem.o: src/pincrem.cpp.o
.PHONY : src/pincrem.o

# target to build an object file
src/pincrem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pincrem.cpp.o
.PHONY : src/pincrem.cpp.o

src/pincrem.i: src/pincrem.cpp.i
.PHONY : src/pincrem.i

# target to preprocess a source file
src/pincrem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pincrem.cpp.i
.PHONY : src/pincrem.cpp.i

src/pincrem.s: src/pincrem.cpp.s
.PHONY : src/pincrem.s

# target to generate assembly for a file
src/pincrem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pincrem.cpp.s
.PHONY : src/pincrem.cpp.s

src/randomsearch.o: src/randomsearch.cpp.o
.PHONY : src/randomsearch.o

# target to build an object file
src/randomsearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/randomsearch.cpp.o
.PHONY : src/randomsearch.cpp.o

src/randomsearch.i: src/randomsearch.cpp.i
.PHONY : src/randomsearch.i

# target to preprocess a source file
src/randomsearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/randomsearch.cpp.i
.PHONY : src/randomsearch.cpp.i

src/randomsearch.s: src/randomsearch.cpp.s
.PHONY : src/randomsearch.s

# target to generate assembly for a file
src/randomsearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/randomsearch.cpp.s
.PHONY : src/randomsearch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/AGE_posicion.o"
	@echo "... src/AGE_posicion.i"
	@echo "... src/AGE_posicion.s"
	@echo "... src/AGE_uniforme.o"
	@echo "... src/AGE_uniforme.i"
	@echo "... src/AGE_uniforme.s"
	@echo "... src/AGG_posicion.o"
	@echo "... src/AGG_posicion.i"
	@echo "... src/AGG_posicion.s"
	@echo "... src/AGG_uniforme.o"
	@echo "... src/AGG_uniforme.i"
	@echo "... src/AGG_uniforme.s"
	@echo "... src/AM_1.o"
	@echo "... src/AM_1.i"
	@echo "... src/AM_1.s"
	@echo "... src/AM_2.o"
	@echo "... src/AM_2.i"
	@echo "... src/AM_2.s"
	@echo "... src/AM_3.o"
	@echo "... src/AM_3.i"
	@echo "... src/AM_3.s"
	@echo "... src/AM_comun.o"
	@echo "... src/AM_comun.i"
	@echo "... src/AM_comun.s"
	@echo "... src/MDD.o"
	@echo "... src/MDD.i"
	@echo "... src/MDD.s"
	@echo "... src/brutesearch.o"
	@echo "... src/brutesearch.i"
	@echo "... src/brutesearch.s"
	@echo "... src/greedy.o"
	@echo "... src/greedy.i"
	@echo "... src/greedy.s"
	@echo "... src/localsearch_rand.o"
	@echo "... src/localsearch_rand.i"
	@echo "... src/localsearch_rand.s"
	@echo "... src/pincrem.o"
	@echo "... src/pincrem.i"
	@echo "... src/pincrem.s"
	@echo "... src/randomsearch.o"
	@echo "... src/randomsearch.i"
	@echo "... src/randomsearch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

